#!/usr/bin/env python3
"""Append Spanish translations to faq.ts"""

def ts_string(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s

def section(title, body):
    return {"title": title, "body": body}

def write_lang(f, lang, sections):
    f.write(f'  "{lang}": [\n')
    for i, sec in enumerate(sections):
        t = ts_string(sec["title"])
        b = ts_string(sec["body"])
        f.write(f'    {{\n')
        f.write(f'      title: "{t}",\n')
        f.write(f'      body: "{b}",\n')
        f.write(f'    }},\n')
    f.write(f'  ],\n\n')

es = [
    section("¿Qué es nullchat?",
        "nullchat es una sala de chat anónima con cifrado de extremo a extremo que no requiere cuentas, correos electrónicos, números de teléfono ni información personal de ningún tipo. Ingresas un secreto compartido — una contraseña — y cualquier otra persona que ingrese la misma contraseña llega a la misma sala. Eso es todo."),
    section("¿Cómo me uno a una sala?",
        "Tú y la persona con la que quieres hablar acuerdan un secreto compartido con antelación — en persona, por una llamada telefónica, como quieran. Ambos escriben ese secreto en nullchat y están en la misma sala cifrada. No hay lista de salas, no hay directorio, no hay forma de buscar. Si no conoces el secreto, la sala no existe para ti."),
    section("¿Cómo debo elegir un secreto compartido?",
        "Tu secreto compartido es la pieza más importante de tu seguridad. Es tanto la llave de tu sala como la llave de tu cifrado — si alguien lo adivina, puede leer todo. Trátalo como una contraseña de una caja fuerte.\n\nElige algo largo, aleatorio e imposible de adivinar. Un secreto fuerte tiene al menos 5–6 palabras aleatorias o más de 20 caracteres mixtos. Evita nombres, fechas, frases comunes, letras de canciones o cualquier cosa que alguien pueda encontrar en tus redes sociales. Nunca reutilices un secreto en diferentes conversaciones o salas.\n\nComparte tu secreto a través de un canal seguro y fuera de banda — en persona es lo mejor. Una llamada telefónica es aceptable. Nunca lo envíes por mensaje de texto, correo electrónico, mensaje directo o cualquier plataforma que registre mensajes. Si sospechas que un secreto ha sido comprometido, deja de usarlo inmediatamente y acuerda uno nuevo a través de un canal seguro.\n\nEl indicador de fortaleza en la pantalla de ingreso te da una idea aproximada de cuán resistente es tu secreto a ataques de fuerza bruta, pero ningún indicador sustituye el buen juicio. Ante la duda, hazlo más largo y más aleatorio."),
    section("¿Cómo funciona el cifrado?",
        "Cuando ingresas tu secreto compartido, dos cosas suceden completamente en tu navegador:\n\n1. El secreto se procesa a través de Argon2id — una función de derivación de claves con uso intensivo de memoria — usando un salt separado por dominio para producir un ID de sala. Este hash se envía al servidor para que sepa a qué sala conectarte. El servidor nunca ve tu secreto real.\n\n2. El secreto pasa por una segunda derivación independiente de Argon2id (64 MiB de memoria, 3 iteraciones) para producir una clave de cifrado de 256 bits. Esta clave nunca sale de tu navegador. Argon2id requiere grandes bloques de RAM por intento, haciendo que los ataques de fuerza bruta con GPU y ASIC contra tu contraseña sean órdenes de magnitud más difíciles que con KDFs tradicionales.\n\nCada mensaje que envías se cifra con NaCl secretbox (XSalsa20-Poly1305) usando esa clave antes de salir de tu dispositivo. El servidor recibe, almacena y retransmite solo texto cifrado — bloques cifrados que no tienen sentido sin la clave. No podemos leer tus mensajes. Nadie puede, a menos que conozca el secreto compartido."),
    section("¿Qué ve el servidor?",
        "El servidor ve:\n• Un hash derivado de Argon2id (el ID de sala) — no tu contraseña\n• Bloques de texto cifrado — no tus mensajes\n• El número de conexiones activas en una sala\n• Marcas de tiempo de cuándo se recibieron los bloques cifrados\n\nEl servidor NO ve:\n• Tu secreto compartido / contraseña\n• El contenido de tus mensajes\n• Tu identidad o nombre de usuario (los alias están cifrados dentro de los mensajes)\n• Tu dirección IP (eliminada en el borde por nuestro proveedor de alojamiento)"),
    section("¿Qué es el relleno de mensajes?",
        "Antes del cifrado, cada mensaje se rellena a un bloque fijo de 8.192 bytes usando un prefijo de longitud de 2 bytes seguido del contenido del mensaje y ruido aleatorio. Esto significa que un mensaje corto como \"hola\" produce exactamente el mismo tamaño de texto cifrado que un mensaje de longitud máxima. Sin relleno, un observador podría adivinar el contenido del mensaje basándose en la longitud del texto cifrado. El relleno de ruido aleatorio (no ceros) asegura que no haya un patrón distinguible en el texto plano antes del cifrado. El relleno elimina este canal lateral por completo."),
    section("¿Qué es la ofuscación de marcas de tiempo?",
        "Las marcas de tiempo incluidas en los mensajes se redondean al minuto más cercano antes del cifrado. Esto previene ataques de correlación temporal donde un observador podría emparejar patrones de mensajes entre diferentes canales comparando marcas de tiempo exactas."),
    section("¿Cuánto duran los mensajes?",
        "Los mensajes usan un sistema de temporizadores escalonado:\n\n• Buzón muerto (primer mensaje): Un mensaje permanece cifrado en el servidor hasta 24 horas, esperando una respuesta. El remitente puede irse y volver a verificar sin activar ninguna cuenta regresiva. Simplemente entrar a la sala no quema el mensaje.\n\n• Ambos usuarios presentes: Cuando una segunda persona se une a la sala, todos los mensajes no leídos comienzan inmediatamente una cuenta regresiva de destrucción de 5 minutos. Cada nuevo mensaje enviado mientras ambos usuarios están presentes también se autodestruye en 5 minutos. No se requiere ninguna acción — la presencia sola confirma que el mensaje está siendo leído.\n\n• Botón de Recibido: Si recoges un mensaje de buzón muerto mientras estás solo en la sala, puedes presionar el botón \"Recibido\" para confirmar manualmente la recepción e iniciar la destrucción de 5 minutos. Este botón solo aparece una vez — durante la recogida inicial del buzón muerto — y no está disponible durante conversaciones activas.\n\n• Conversación activa: Una vez que una sala ha tenido respuestas, los mensajes subsiguientes tienen una ventana de 6 horas si el destinatario no está presente. Si ambos usuarios están conectados, los mensajes se destruyen en 5 minutos automáticamente.\n\n• Tope máximo: Cualquier mensaje no leído se elimina cuando su temporizador expira (24 horas para buzones muertos, 6 horas para mensajes activos) independientemente de si fue confirmado.\n\nNo hay archivo, no hay respaldo, no hay forma de recuperar un mensaje eliminado."),
    section("¿Qué es el buzón muerto?",
        "nullchat funciona como un buzón muerto digital. En la tradición del espionaje, un buzón muerto es un método para pasar información entre dos personas sin que necesiten encontrarse o estar en el mismo lugar al mismo tiempo. nullchat funciona de la misma manera.\n\nIngresas el secreto compartido, dejas un mensaje cifrado y te desconectas. El mensaje permanece en el servidor — cifrado e ilegible para cualquiera, incluyéndonos — hasta 24 horas. Tu contacto ingresa el mismo secreto cuando esté listo y recoge el mensaje. Cuando el destinatario se une y ambos usuarios están presentes, todos los mensajes en espera comienzan inmediatamente una cuenta regresiva de destrucción de 5 minutos — la presencia sola es prueba de recepción. Si el destinatario recoge el mensaje mientras está solo, puede presionar el botón único \"Recibido\" para confirmar manualmente la recepción e iniciar la destrucción, o simplemente responder. Una vez que comienza la destrucción, el mensaje se destruye permanentemente después de 5 minutos.\n\nEl remitente puede reconectarse de forma segura en cualquier momento para verificar si su mensaje sigue esperando — sin activar ninguna cuenta regresiva, siempre que sea el único en la sala. Ninguna de las partes necesita estar en línea al mismo tiempo. Ninguna de las partes necesita una cuenta. Ninguna de las partes es identificable. El servidor nunca sabe quién dejó el mensaje o quién lo recogió — solo que un bloque cifrado fue almacenado y luego recuperado. Después de la destrucción, no hay evidencia de que el intercambio haya ocurrido."),
    section("¿Cuánto duran las salas?",
        "Una sala existe mientras tenga conexiones activas o mensajes no expirados. Una vez que la última persona se desconecta y todos los mensajes han expirado o sido destruidos, la sala desaparece. No hay estado persistente de sala. Si nunca se envían mensajes, la sala es solo una conexión en vivo — nada se almacena y desaparece en el momento en que todos se van."),
    section("¿Qué es el botón Terminar?",
        "Terminar elimina inmediatamente cada mensaje que enviaste durante tu sesión actual del servidor para todos en la sala. Otros participantes verán tus mensajes desaparecer de su pantalla en tiempo real. Luego te desconectas de la sala. Usa esto si necesitas irte sin dejar rastro."),
    section("¿Qué es el botón Salir?",
        "Salir simplemente te desconecta de la sala. Tus mensajes permanecen en el servidor — los mensajes no leídos siguen esperando (hasta 24 horas), y los mensajes ya leídos continúan su cuenta regresiva de destrucción de 5 minutos. Si te reúnes a la sala más tarde, obtendrás un nuevo alias aleatorio — no hay forma de vincular tu identidad anterior con la nueva."),
    section("¿Qué son los alias aleatorios?",
        "Cuando entras a una sala, se te asigna un código hexadecimal aleatorio de 8 caracteres (como \"a9f2b71c\") como tu alias. Este alias se genera en tu navegador, se cifra dentro de cada mensaje y nunca se envía al servidor en texto plano. Si te desconectas y te reconectas, obtienes un nuevo alias. No hay forma de reservar, elegir o mantener un alias."),
    section("¿Hay un límite de participantes?",
        "Cada sala soporta hasta 50 conexiones simultáneas. Si la sala está llena, verás un mensaje de \"Sala llena\". Este límite existe para mantener las salas íntimas y para prevenir el abuso."),
    section("¿Hay limitación de velocidad?",
        "Sí. Cada conexión está limitada a 1 mensaje por segundo. Esto previene el spam y el abuso sin requerir ninguna verificación de identidad. Si envías mensajes demasiado rápido, verás un breve aviso de \"Más despacio\"."),
    section("¿Puedo acceder a nullchat a través de Tor?",
        "nullchat está disponible como un servicio oculto de Tor para usuarios en regiones censuradas o cualquier persona que quiera una capa adicional de anonimato. Abre el Navegador Tor y navega a:\n\n{onion_link}\n\nPor defecto, tanto la versión clearnet como la de Tor se conectan al mismo backend — los usuarios en cualquiera de las dos pueden comunicarse entre sí en las mismas salas usando el mismo secreto compartido. El servicio .onion se enruta a través de la red de Tor sin Cloudflare, sin CDN y sin infraestructura de terceros entre tú y el servidor. Tor enruta tu conexión a través de múltiples relés cifrados, por lo que ni el servidor ni ningún observador pueden determinar tu dirección IP real o ubicación. El servicio .onion usa HTTP plano, lo cual es esperado y seguro — Tor mismo proporciona cifrado de extremo a extremo entre tu navegador y el servidor. Todo el mismo cifrado a nivel de aplicación (NaCl secretbox, derivación de clave Argon2id) se aplica encima de eso. Nota: El Navegador Tor debe estar configurado en el nivel de seguridad \"Estándar\" para que nullchat funcione, ya que la aplicación requiere JavaScript."),
    section("¿Qué es una sala solo para Tor?",
        "Al acceder a nullchat a través del servicio oculto .onion, tienes la opción de habilitar \"Sala solo para Tor\" — un interruptor que aparece en la pantalla de ingreso de contraseña. Cuando está habilitado, tu sala se coloca en un espacio de nombres separado al que solo otros usuarios de Tor con el mismo interruptor habilitado pueden acceder. Los usuarios de clearnet nunca pueden unirse a una sala solo para Tor, incluso si conocen el secreto compartido.\n\nEsto proporciona un nivel de seguridad más alto que las salas compartidas por defecto:\n\n• Ambas partes son enrutadas a través de la red onion multi-salto de Tor — la dirección IP real o ubicación de ninguna de las partes es visible para nadie, incluido el servidor.\n• No hay búsquedas DNS, no hay CDN y ninguna infraestructura de terceros toca la conexión en ningún punto.\n• El análisis de tráfico es significativamente más difícil porque ambos lados se benefician del relleno de relés de Tor combinado con el relleno de conexión propio de nullchat (tramas ficticias aleatorias enviadas a intervalos aleatorios).\n• No hay un participante de clearnet cuya metadata de conexión más débil pueda correlacionarse con la conversación.\n\nEres tan anónimo como el eslabón más débil de la conversación. En una sala por defecto, la conexión de un participante de clearnet toca resolvedores DNS, infraestructura CDN y enrutamiento estándar de internet — todo lo cual puede ser observado o requerido judicialmente para obtener metadata sobre quién se conectó, cuándo y desde dónde. El interruptor de solo Tor elimina este riesgo por completo asegurando que cada participante tenga el mismo nivel de anonimato en la capa de red.\n\nAmbas partes deben acordar habilitar el interruptor — funciona de la misma manera que acordar el secreto compartido. El encabezado del chat muestra \"SOLO TOR\" en verde cuando está activo, o \"CLEARNET\" en rojo para salas estándar, para que siempre sepas en qué modo estás."),
    section("¿Qué es el tiempo de espera por inactividad?",
        "Si estás inactivo durante 15 minutos — sin escribir, sin tocar, sin desplazarte — nullchat te desconectará automáticamente y te regresará a la pantalla de ingreso de contraseña. Una advertencia aparece a los 13 minutos dándote la opción de quedarte. Esto protege tu sesión si te alejas de tu dispositivo, previniendo que los mensajes se destruyan mientras nadie los está leyendo activamente, y asegurando que el chat no quede visible en una pantalla desatendida."),
    section("¿Qué hay de las direcciones IP?",
        "En la clearnet (nullchat.org), la aplicación está alojada en la red de borde de Cloudflare. Tu dirección IP se maneja en la capa de infraestructura y nunca es leída, registrada o almacenada por el código de la aplicación. El código del servidor no accede a las cabeceras de IP. No tenemos ningún mecanismo para identificarte por dirección de red.\n\nEn el servicio oculto de Tor (.onion), tu dirección IP nunca es visible para el servidor — el enrutamiento onion de Tor asegura anonimato completo a nivel de red. El servidor solo ve conexiones desde la red Tor, sin forma de rastrearlas hasta ti."),
    section("¿Hay cookies o rastreadores?",
        "No. nullchat no establece cookies, no usa analíticas, no carga scripts de terceros, no incorpora píxeles de seguimiento y no hace solicitudes externas. Las cabeceras de Política de Seguridad de Contenido lo aplican a nivel del navegador. Puedes verificar esto en las herramientas de desarrollador de tu navegador."),
    section("¿Por qué no puedo enviar enlaces, imágenes o archivos?",
        "Por diseño. nullchat es solo texto — no se pueden enviar ni renderizar enlaces, imágenes, archivos adjuntos ni medios de ningún tipo. Esta es una decisión de seguridad deliberada, no una limitación. Los enlaces clicables y los medios incrustados son la superficie de ataque principal para exploits de día cero utilizados por spyware comercial como Pegasus, Predator y herramientas de vigilancia similares. Un solo enlace o archivo malicioso puede comprometer silenciosamente un dispositivo entero. Al reducir el chat a solo texto plano, nullchat elimina este vector de ataque por completo. No hay nada que hacer clic, nada que descargar y nada que renderizar — lo que significa nada que explotar."),
    section("¿Puedo copiar o capturar pantallas de los mensajes?",
        "nullchat desalienta activamente la captura del contenido de los mensajes. La selección de texto y la copia están deshabilitadas en el área de chat, los menús contextuales de clic derecho están bloqueados y los atajos de teclado comunes para capturas de pantalla son interceptados. La API de Captura de Pantalla del navegador también está bloqueada a través de las cabeceras de Permissions-Policy, previniendo que las herramientas de grabación de pantalla basadas en web capturen la página.\n\nEstas son protecciones basadas en fricción, no garantías absolutas. Un usuario determinado siempre puede fotografiar su pantalla con otro dispositivo o usar herramientas a nivel del sistema operativo que evitan las restricciones del navegador. El objetivo es hacer que la captura casual sea difícil y reforzar la expectativa de que las conversaciones en nullchat no están destinadas a ser guardadas."),
    section("¿Qué es el tráfico señuelo?",
        "nullchat envía automáticamente mensajes ficticios cifrados a intervalos aleatorios (cada 10–60 segundos) mientras estás conectado a una sala. Estos mensajes señuelo son indistinguibles de los mensajes reales — tienen el mismo tamaño (gracias al relleno fijo), están cifrados con la misma clave y se retransmiten por la misma ruta del servidor. El cliente del destinatario los descarta silenciosamente después del descifrado.\n\nEl tráfico señuelo derrota el análisis de tráfico. Sin él, un observador que monitorea el tráfico de red podría determinar cuándo ocurre comunicación real basándose en cuándo se envían los bloques cifrados. Con los señuelos, hay un flujo constante de tráfico de apariencia idéntica independientemente de si alguien está realmente escribiendo — haciendo imposible distinguir mensajes reales del ruido."),
    section("¿Qué es el relleno de conexión?",
        "El servidor envía tramas binarias de longitud aleatoria (64–512 bytes de datos aleatorios) a cada cliente conectado a intervalos aleatorios (cada 5–30 segundos). Estas tramas no son mensajes — son puro ruido que el cliente ignora silenciosamente. Combinado con el tráfico señuelo del lado del cliente, el relleno de conexión asegura que los patrones de tráfico de red no revelen nada sobre si se está produciendo comunicación real, cuántos mensajes se están intercambiando o cuándo están activos los participantes."),
    section("¿Qué es la tecla de pánico?",
        "Presionar tres veces la tecla Escape borra instantáneamente tu sesión. Cuando se activa, nullchat envía un comando de terminación al servidor (eliminando todos tus mensajes), cierra la conexión WebSocket, pone a cero la clave de cifrado en memoria, limpia el DOM, borra sessionStorage y localStorage, limpia el portapapeles y redirige tu navegador a google.com. Todo el proceso toma menos de un segundo. Si el navegador intenta restaurar la página desde la caché (por ejemplo, con el botón de retroceso), el borrado se activa automáticamente de nuevo. Usa esto si necesitas borrar inmediatamente toda evidencia de la conversación de tu pantalla y navegador."),
    section("¿Qué es el modo esteganográfico?",
        "El modo esteganográfico disfraza la interfaz de nullchat como un editor de documentos. Presiona Shift cinco veces rápidamente para activarlo. Toda la interfaz se transforma — la interfaz oscura del chat se reemplaza con una interfaz de edición de documentos de aspecto familiar con barra de herramientas y barra de menú. Los mensajes aparecen como párrafos en el cuerpo del documento, y tu entrada se mezcla como escritura activa. Todo el cifrado, los temporizadores de destrucción y las funciones de seguridad continúan operando normalmente por debajo.\n\nEsto es útil si alguien está mirando por encima de tu hombro o si tu pantalla es visible para otros. A primera vista, parece que estás editando un documento, no teniendo una conversación cifrada. Presiona Shift cinco veces de nuevo para volver a la vista normal del chat."),
    section("¿nullchat limpia automáticamente el portapapeles?",
        "Sí. Si algo se copia mientras estás en una sala de chat, nullchat limpia automáticamente tu portapapeles después de 15 segundos. El portapapeles también se borra cuando cierras la pestaña o navegas a otra página, e inmediatamente si usas la tecla de pánico. Esto previene que el contenido de los mensajes permanezca en tu portapapeles después de que hayas dejado la conversación."),
    section("¿Pueden leer mis mensajes?",
        "No. El servidor es un relé simple. Recibe bloques cifrados y los reenvía. La clave de cifrado se deriva de tu secreto compartido, que nunca sale de tu navegador. No tenemos la clave. No podemos descifrar los bloques. Incluso si el servidor fuera comprometido, el atacante solo obtendría texto cifrado sin sentido."),
    section("¿Pueden las agencias gubernamentales acceder a mis mensajes?",
        "No podemos proporcionar lo que no tenemos. No hay mensajes en texto plano almacenados en ningún lugar. No hay cuentas de usuario que buscar. No hay registros de IP que entregar. Los bloques cifrados se eliminan automáticamente según un horario fijo. Incluso bajo una orden legal válida, lo máximo que podríamos producir es una colección de bloques cifrados y hashes de sala — ninguno de los cuales es útil sin el secreto compartido que solo los participantes conocen."),
    section("¿Es nullchat de código abierto?",
        "Sí. Todo el código — cliente, servidor, cifrado y configuración de infraestructura — está disponible públicamente para auditoría en {github_link}. Puedes verificar que el código que se ejecuta en el servidor coincide con lo publicado, compilarlo tú mismo o alojar tu propia instancia. La transparencia no es opcional para una herramienta que te pide que confíes en ella con tus comunicaciones privadas."),
    section("¿Quién construyó nullchat?",
        "nullchat está construido por Artorias — una empresa de tecnología de inteligencia operada por veteranos con sede en la ciudad de Nueva York. Artorias existe para desmantelar sistemas obsoletos y armar a las organizaciones e individuos más importantes con herramientas diseñadas específicamente para operar en la oscuridad. En su esencia, Artorias se trata de democratizar la inteligencia y el anonimato — asegurando que la capacidad de comunicarse de forma segura y operar sin vigilancia no sea un privilegio reservado para unos pocos. nullchat es una expresión de esa misión: comunicación segura reducida a su esencia, sin compromisos en la integridad criptográfica. Aprende más en {artorias_link}."),
    section("¿Puedo agregar nullchat a mi pantalla de inicio?",
        "Sí. nullchat soporta Agregar a Pantalla de Inicio tanto en iOS como en Android. En iOS Safari, toca el botón de compartir y selecciona \"Agregar a Pantalla de Inicio\". En Android Chrome, toca el menú y selecciona \"Agregar a Pantalla de Inicio\" o \"Instalar aplicación\". Esto crea un acceso directo independiente que abre nullchat sin el chrome del navegador — sin barra de direcciones, sin pestañas. Se ve y se siente como una aplicación nativa.\n\nImportante: nullchat deliberadamente no usa un service worker ni almacena datos en caché sin conexión. No hay modo sin conexión. El acceso directo de la pantalla de inicio simplemente abre el sitio en vivo — nada se almacena en tu dispositivo más allá del acceso directo mismo. Esta es una decisión de seguridad: almacenar en caché páginas de chat cifradas o scripts de service worker en el dispositivo crearía evidencia forense de que se usó nullchat. El acceso directo no deja rastro más allá de su propio ícono, que puede eliminarse en cualquier momento."),
]

outpath = "/Users/christian/whisper/lib/i18n/faq.ts"
with open(outpath, 'a') as f:
    write_lang(f, "es", es)

print("Spanish done")
