#!/usr/bin/env python3
"""Append German translations to faq.ts"""

def ts_string(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s

def section(title, body):
    return {"title": title, "body": body}

def write_lang(f, lang, sections):
    f.write(f'  "{lang}": [\n')
    for i, sec in enumerate(sections):
        t = ts_string(sec["title"])
        b = ts_string(sec["body"])
        f.write(f'    {{\n')
        f.write(f'      title: "{t}",\n')
        f.write(f'      body: "{b}",\n')
        f.write(f'    }},\n')
    f.write(f'  ],\n\n')

de = [
    section("Was ist nullchat?",
        "nullchat ist ein anonymer, Ende-zu-Ende-verschlüsselter Chatraum, der keine Konten, keine E-Mails, keine Telefonnummern und keinerlei persönliche Informationen erfordert. Du gibst ein gemeinsames Geheimnis ein — ein Passwort — und jeder andere, der dasselbe Passwort eingibt, landet im selben Raum. Das ist alles."),
    section("Wie trete ich einem Raum bei?",
        "Du und die Person, mit der du sprechen möchtest, vereinbart im Voraus ein gemeinsames Geheimnis — persönlich, per Telefonanruf, wie auch immer ihr wollt. Ihr beide tippt dieses Geheimnis in nullchat ein und seid im selben verschlüsselten Raum. Es gibt keine Raumliste, kein Verzeichnis, keine Möglichkeit zu suchen. Wenn du das Geheimnis nicht kennst, existiert der Raum für dich nicht."),
    section("Wie sollte ich ein gemeinsames Geheimnis wählen?",
        "Dein gemeinsames Geheimnis ist das wichtigste Element deiner Sicherheit. Es ist sowohl der Schlüssel zu deinem Raum als auch der Schlüssel zu deiner Verschlüsselung — wenn jemand es errät, kann er alles lesen. Behandle es wie das Passwort eines Tresors.\n\nWähle etwas Langes, Zufälliges und Unerratbares. Ein starkes Geheimnis besteht aus mindestens 5–6 zufälligen Wörtern oder mehr als 20 gemischten Zeichen. Vermeide Namen, Daten, gängige Phrasen, Songtexte oder alles, was jemand in deinen sozialen Medien finden könnte. Verwende ein Geheimnis niemals für verschiedene Gespräche oder Räume wieder.\n\nTeile dein Geheimnis über einen sicheren, externen Kanal — persönlich ist am besten. Ein Telefonanruf ist akzeptabel. Sende es niemals per SMS, E-Mail, Direktnachricht oder über eine Plattform, die Nachrichten protokolliert. Wenn du vermutest, dass ein Geheimnis kompromittiert wurde, höre sofort auf es zu verwenden und vereinbare ein neues über einen sicheren Kanal.\n\nDer Stärkeindikator auf dem Eingabebildschirm gibt dir einen groben Eindruck davon, wie widerstandsfähig dein Geheimnis gegen Brute-Force-Angriffe ist, aber kein Indikator ersetzt gutes Urteilsvermögen. Im Zweifelsfall mache es länger und zufälliger."),
    section("Wie funktioniert die Verschlüsselung?",
        "Wenn du dein gemeinsames Geheimnis eingibst, passieren zwei Dinge vollständig in deinem Browser:\n\n1. Das Geheimnis wird durch Argon2id verarbeitet — eine speicherintensive Schlüsselableitungsfunktion — unter Verwendung eines domänengetrennten Salts, um eine Raum-ID zu erzeugen. Dieser Hash wird an den Server gesendet, damit er weiß, mit welchem Raum er dich verbinden soll. Der Server sieht niemals dein tatsächliches Geheimnis.\n\n2. Das Geheimnis durchläuft eine zweite, unabhängige Argon2id-Ableitung (64 MiB Speicher, 3 Iterationen), um einen 256-Bit-Verschlüsselungsschlüssel zu erzeugen. Dieser Schlüssel verlässt niemals deinen Browser. Argon2id erfordert große RAM-Blöcke pro Versuch, wodurch GPU- und ASIC-Brute-Force-Angriffe auf dein Passwort um Größenordnungen schwieriger werden als bei traditionellen KDFs.\n\nJede Nachricht, die du sendest, wird mit NaCl secretbox (XSalsa20-Poly1305) unter Verwendung dieses Schlüssels verschlüsselt, bevor sie dein Gerät verlässt. Der Server empfängt, speichert und leitet nur Chiffretext weiter — verschlüsselte Blobs, die ohne den Schlüssel bedeutungslos sind. Wir können deine Nachrichten nicht lesen. Niemand kann es, es sei denn, er kennt das gemeinsame Geheimnis."),
    section("Was sieht der Server?",
        "Der Server sieht:\n• Einen von Argon2id abgeleiteten Hash (die Raum-ID) — nicht dein Passwort\n• Verschlüsselte Chiffretext-Blobs — nicht deine Nachrichten\n• Die Anzahl aktiver Verbindungen in einem Raum\n• Zeitstempel, wann verschlüsselte Blobs empfangen wurden\n\nDer Server sieht NICHT:\n• Dein gemeinsames Geheimnis / Passwort\n• Deinen Nachrichteninhalt\n• Deine Identität oder deinen Benutzernamen (Aliase sind in den Nachrichten verschlüsselt)\n• Deine IP-Adresse (am Edge von unserem Hosting-Anbieter entfernt)"),
    section("Was ist Nachrichten-Padding?",
        "Vor der Verschlüsselung wird jede Nachricht auf einen festen 8.192-Byte-Block aufgefüllt, unter Verwendung eines 2-Byte-Längenpräfixes, gefolgt vom Nachrichteninhalt und zufälligem Rauschen. Das bedeutet, dass eine kurze Nachricht wie \"hi\" exakt dieselbe Chiffretextgröße erzeugt wie eine Nachricht maximaler Länge. Ohne Padding könnte ein Beobachter den Nachrichteninhalt anhand der Chiffretextlänge erraten. Die zufällige Rauschfüllung (keine Nullen) stellt sicher, dass es kein unterscheidbares Muster im Klartext vor der Verschlüsselung gibt. Padding eliminiert diesen Seitenkanal vollständig."),
    section("Was ist Zeitstempel-Verschleierung?",
        "In Nachrichten enthaltene Zeitstempel werden vor der Verschlüsselung auf die nächste Minute gerundet. Dies verhindert Timing-Korrelationsangriffe, bei denen ein Beobachter Nachrichtenmuster über verschiedene Kanäle hinweg durch den Vergleich exakter Zeitstempel abgleichen könnte."),
    section("Wie lange bleiben Nachrichten bestehen?",
        "Nachrichten verwenden ein gestaffeltes Timer-System:\n\n• Toter Briefkasten (erste Nachricht): Eine Nachricht liegt verschlüsselt auf dem Server für bis zu 24 Stunden und wartet auf eine Antwort. Der Absender kann gehen und wiederkommen, um nachzusehen, ohne einen Countdown auszulösen. Das einfache Betreten des Raums verbrennt die Nachricht nicht.\n\n• Beide Benutzer anwesend: Wenn eine zweite Person dem Raum beitritt, beginnen alle ungelesenen Nachrichten sofort einen 5-Minuten-Lösch-Countdown. Jede neue Nachricht, die gesendet wird, während beide Benutzer anwesend sind, wird ebenfalls automatisch in 5 Minuten gelöscht. Keine Aktion ist erforderlich — die Anwesenheit allein bestätigt, dass die Nachricht gelesen wird.\n\n• Empfangen-Button: Wenn du eine Nachricht aus dem toten Briefkasten aufnimmst, während du allein im Raum bist, kannst du den \"Empfangen\"-Button drücken, um den Empfang manuell zu bestätigen und die 5-Minuten-Löschung zu starten. Dieser Button erscheint nur einmal — beim erstmaligen Abholen aus dem toten Briefkasten — und ist während aktiver Gespräche nicht verfügbar.\n\n• Aktives Gespräch: Sobald ein Raum Antworten gesehen hat, haben nachfolgende Nachrichten ein 6-Stunden-Fenster, wenn der Empfänger nicht anwesend ist. Wenn beide Benutzer verbunden sind, werden Nachrichten automatisch in 5 Minuten gelöscht.\n\n• Absolute Obergrenze: Jede ungelesene Nachricht wird nach Ablauf ihres Timers gelöscht (24 Stunden für tote Briefkästen, 6 Stunden für aktive Nachrichten), unabhängig davon, ob sie bestätigt wurde.\n\nEs gibt kein Archiv, kein Backup, keine Möglichkeit, eine gelöschte Nachricht wiederherzustellen."),
    section("Was ist der tote Briefkasten?",
        "nullchat funktioniert als digitaler toter Briefkasten. In der traditionellen Geheimdiensttradition ist ein toter Briefkasten eine Methode, um Informationen zwischen zwei Personen auszutauschen, ohne dass sie sich jemals treffen oder zur gleichen Zeit am gleichen Ort sein müssen. nullchat funktioniert genauso.\n\nDu gibst das gemeinsame Geheimnis ein, hinterlässt eine verschlüsselte Nachricht und trennst die Verbindung. Die Nachricht liegt auf dem Server — verschlüsselt und für niemanden lesbar, einschließlich uns — für bis zu 24 Stunden. Dein Kontakt gibt dasselbe Geheimnis ein, wenn er bereit ist, und holt die Nachricht ab. Wenn der Empfänger beitritt und beide Benutzer anwesend sind, beginnen alle wartenden Nachrichten sofort einen 5-Minuten-Lösch-Countdown — die Anwesenheit allein ist der Beweis des Empfangs. Wenn der Empfänger die Nachricht abholt, während er allein ist, kann er den einmaligen \"Empfangen\"-Button drücken, um den Empfang manuell zu bestätigen und die Löschung zu starten, oder einfach antworten. Sobald die Löschung beginnt, wird die Nachricht nach 5 Minuten dauerhaft zerstört.\n\nDer Absender kann sich jederzeit sicher wieder verbinden, um zu überprüfen, ob seine Nachricht noch wartet — ohne einen Countdown auszulösen, solange er der Einzige im Raum ist. Keine der Parteien muss zur gleichen Zeit online sein. Keine der Parteien braucht ein Konto. Keine der Parteien ist identifizierbar. Der Server weiß nie, wer die Nachricht hinterlassen hat oder wer sie abgeholt hat — nur, dass ein verschlüsselter Blob gespeichert und später abgerufen wurde. Nach der Löschung gibt es keinen Beweis, dass der Austausch jemals stattgefunden hat."),
    section("Wie lange bestehen Räume?",
        "Ein Raum existiert, solange er aktive Verbindungen oder nicht abgelaufene Nachrichten hat. Sobald die letzte Person die Verbindung trennt und alle Nachrichten abgelaufen oder gelöscht sind, ist der Raum verschwunden. Es gibt keinen persistenten Raumzustand. Wenn nie Nachrichten gesendet werden, ist der Raum nur eine Live-Verbindung — nichts wird gespeichert, und er verschwindet in dem Moment, in dem alle gehen."),
    section("Was ist der Beenden-Button?",
        "Beenden löscht sofort jede Nachricht, die du während deiner aktuellen Sitzung gesendet hast, vom Server für alle im Raum. Andere Teilnehmer werden sehen, wie deine Nachrichten in Echtzeit von ihrem Bildschirm verschwinden. Du wirst dann vom Raum getrennt. Verwende dies, wenn du ohne Spur gehen musst."),
    section("Was ist der Verlassen-Button?",
        "Verlassen trennt dich einfach vom Raum. Deine Nachrichten bleiben auf dem Server — ungelesene Nachrichten warten weiter (bis zu 24 Stunden), und bereits gelesene Nachrichten setzen ihren 5-Minuten-Lösch-Countdown fort. Wenn du dem Raum später wieder beitrittst, bekommst du einen neuen zufälligen Alias — es gibt keine Möglichkeit, deine alte und neue Identität zu verknüpfen."),
    section("Was sind die zufälligen Aliase?",
        "Wenn du einen Raum betrittst, wird dir ein zufälliger 8-Zeichen-Hex-Code (wie \"a9f2b71c\") als Alias zugewiesen. Dieser Alias wird in deinem Browser generiert, in jeder Nachricht verschlüsselt und wird niemals im Klartext an den Server gesendet. Wenn du die Verbindung trennst und dich wieder verbindest, bekommst du einen neuen Alias. Es gibt keine Möglichkeit, einen Alias zu reservieren, auszuwählen oder beizubehalten."),
    section("Gibt es eine Teilnehmerbegrenzung?",
        "Jeder Raum unterstützt bis zu 50 gleichzeitige Verbindungen. Wenn der Raum voll ist, siehst du eine \"Raum ist voll\"-Meldung. Diese Begrenzung existiert, um Räume intim zu halten und Missbrauch zu verhindern."),
    section("Gibt es eine Ratenbegrenzung?",
        "Ja. Jede Verbindung ist auf 1 Nachricht pro Sekunde begrenzt. Dies verhindert Spam und Missbrauch, ohne eine Identitätsüberprüfung zu erfordern. Wenn du Nachrichten zu schnell sendest, siehst du einen kurzen \"Langsamer\"-Hinweis."),
    section("Kann ich über Tor auf nullchat zugreifen?",
        "nullchat ist als Tor-Hidden-Service für Benutzer in zensierten Regionen oder für jeden verfügbar, der eine zusätzliche Anonymitätsschicht wünscht. Öffne den Tor-Browser und navigiere zu:\n\n{onion_link}\n\nStandardmäßig verbinden sich sowohl die Clearnet- als auch die Tor-Version mit demselben Backend — Benutzer auf beiden Seiten können in denselben Räumen mit demselben gemeinsamen Geheimnis miteinander kommunizieren. Der .onion-Dienst wird über das Tor-Netzwerk geroutet, ohne Cloudflare, ohne CDN und ohne Drittanbieter-Infrastruktur zwischen dir und dem Server. Tor leitet deine Verbindung über mehrere verschlüsselte Relais, sodass weder der Server noch ein Beobachter deine echte IP-Adresse oder deinen Standort bestimmen kann. Der .onion-Dienst verwendet unverschlüsseltes HTTP, was erwartet und sicher ist — Tor selbst bietet Ende-zu-Ende-Verschlüsselung zwischen deinem Browser und dem Server. Dieselbe Anwendungsverschlüsselung (NaCl secretbox, Argon2id-Schlüsselableitung) gilt zusätzlich. Hinweis: Der Tor-Browser muss auf die Sicherheitsstufe \"Standard\" eingestellt sein, damit nullchat funktioniert, da die App JavaScript erfordert."),
    section("Was ist ein Nur-Tor-Raum?",
        "Wenn du über den .onion-Hidden-Service auf nullchat zugreifst, hast du die Möglichkeit, \"Nur-Tor-Raum\" zu aktivieren — ein Schalter, der auf dem Passworteingabebildschirm erscheint. Wenn aktiviert, wird dein Raum in einen separaten Namensraum platziert, auf den nur andere Tor-Benutzer mit demselben aktivierten Schalter zugreifen können. Clearnet-Benutzer können niemals einem Nur-Tor-Raum beitreten, selbst wenn sie das gemeinsame Geheimnis kennen.\n\nDies bietet ein höheres Sicherheitsniveau als die standardmäßigen geteilten Räume:\n\n• Beide Parteien werden über Tors Multi-Hop-Onion-Netzwerk geroutet — die echte IP-Adresse oder der Standort keiner Partei ist für irgendjemanden sichtbar, einschließlich des Servers.\n• Keine DNS-Abfragen, kein CDN und keine Drittanbieter-Infrastruktur berührt die Verbindung an irgendeinem Punkt.\n• Verkehrsanalyse ist erheblich schwieriger, da beide Seiten von Tors Relay-Padding profitieren, kombiniert mit nullchats eigenem Verbindungs-Padding (zufällige Dummy-Frames, die in zufälligen Intervallen gesendet werden).\n• Es gibt keinen Clearnet-Teilnehmer, dessen schwächere Verbindungsmetadaten mit dem Gespräch korreliert werden könnten.\n\nDu bist nur so anonym wie das schwächste Glied im Gespräch. In einem Standardraum berührt die Verbindung eines Clearnet-Teilnehmers DNS-Resolver, CDN-Infrastruktur und Standard-Internet-Routing — all dies kann beobachtet oder gerichtlich angeordnet werden, um Metadaten darüber zu erhalten, wer sich verbunden hat, wann und von wo. Der Nur-Tor-Schalter eliminiert dieses Risiko vollständig, indem sichergestellt wird, dass jeder Teilnehmer dasselbe Niveau an Netzwerkschicht-Anonymität hat.\n\nBeide Parteien müssen der Aktivierung des Schalters zustimmen — es funktioniert genauso wie die Vereinbarung des gemeinsamen Geheimnisses. Der Chat-Header zeigt \"NUR TOR\" in Grün an, wenn aktiv, oder \"CLEARNET\" in Rot für Standardräume, damit du immer weißt, in welchem Modus du bist."),
    section("Was ist das Inaktivitäts-Timeout?",
        "Wenn du 15 Minuten inaktiv bist — kein Tippen, kein Antippen, kein Scrollen — wird nullchat dich automatisch trennen und zum Passworteingabebildschirm zurückbringen. Eine Warnung erscheint bei 13 Minuten und gibt dir die Möglichkeit zu bleiben. Dies schützt deine Sitzung, wenn du von deinem Gerät weggehst, verhindert, dass Nachrichten verbrennen, während niemand aktiv liest, und stellt sicher, dass der Chat nicht auf einem unbeaufsichtigten Bildschirm sichtbar bleibt."),
    section("Was ist mit IP-Adressen?",
        "Im Clearnet (nullchat.org) wird die Anwendung auf dem Edge-Netzwerk von Cloudflare gehostet. Deine IP-Adresse wird auf der Infrastrukturebene behandelt und wird vom Anwendungscode niemals gelesen, protokolliert oder gespeichert. Der Servercode greift nicht auf IP-Header zu. Wir haben keinen Mechanismus, um dich anhand deiner Netzwerkadresse zu identifizieren.\n\nBeim Tor-Hidden-Service (.onion) ist deine IP-Adresse für den Server überhaupt nicht sichtbar — Tors Onion-Routing gewährleistet vollständige Anonymität auf Netzwerkebene. Der Server sieht nur Verbindungen aus dem Tor-Netzwerk, ohne die Möglichkeit, sie zu dir zurückzuverfolgen."),
    section("Gibt es Cookies oder Tracker?",
        "Nein. nullchat setzt keine Cookies, verwendet keine Analytik, lädt keine Drittanbieter-Skripte, bettet keine Tracking-Pixel ein und stellt keine externen Anfragen. Die Content-Security-Policy-Header erzwingen dies auf Browserebene. Du kannst dies in den Entwicklertools deines Browsers überprüfen."),
    section("Warum kann ich keine Links, Bilder oder Dateien senden?",
        "Absichtlich. nullchat ist rein textbasiert — keine Links, Bilder, Dateianhänge oder Medien jeglicher Art können gesendet oder gerendert werden. Dies ist eine bewusste Sicherheitsentscheidung, keine Einschränkung. Klickbare Links und eingebettete Medien sind die primäre Angriffsfläche für Zero-Day-Exploits, die von kommerzieller Spyware wie Pegasus, Predator und ähnlichen Überwachungstools verwendet werden. Ein einziger bösartiger Link oder eine Datei kann ein ganzes Gerät stillschweigend kompromittieren. Indem der Chat auf reinen Text reduziert wird, eliminiert nullchat diesen Angriffsvektor vollständig. Es gibt nichts zum Anklicken, nichts zum Herunterladen und nichts zum Rendern — was bedeutet, nichts zum Ausnutzen."),
    section("Kann ich Nachrichten kopieren oder Screenshots machen?",
        "nullchat verhindert aktiv das Erfassen von Nachrichteninhalten. Textauswahl und Kopieren sind im Chatbereich deaktiviert, Rechtsklick-Kontextmenüs sind blockiert und gängige Screenshot-Tastenkürzel werden abgefangen. Die Screen-Capture-API des Browsers ist ebenfalls über Permissions-Policy-Header blockiert, was webbasierte Bildschirmaufnahme-Tools daran hindert, die Seite aufzuzeichnen.\n\nDies sind reibungsbasierte Schutzmaßnahmen, keine absoluten Garantien. Ein entschlossener Benutzer kann immer seinen Bildschirm mit einem anderen Gerät fotografieren oder Betriebssystem-Tools verwenden, die Browser-Einschränkungen umgehen. Das Ziel ist es, beiläufiges Erfassen schwierig zu machen und die Erwartung zu verstärken, dass Gespräche in nullchat nicht zum Speichern bestimmt sind."),
    section("Was ist Tarnverkehr?",
        "nullchat sendet automatisch verschlüsselte Dummy-Nachrichten in zufälligen Intervallen (alle 10–60 Sekunden), während du mit einem Raum verbunden bist. Diese Tarnnachrichten sind von echten Nachrichten nicht zu unterscheiden — sie haben dieselbe Größe (dank festem Padding), werden mit demselben Schlüssel verschlüsselt und über denselben Serverpfad weitergeleitet. Der Client des Empfängers verwirft sie nach der Entschlüsselung stillschweigend.\n\nTarnverkehr verhindert Verkehrsanalyse. Ohne ihn könnte ein Beobachter, der den Netzwerkverkehr überwacht, feststellen, wann echte Kommunikation stattfindet, basierend darauf, wann verschlüsselte Blobs gesendet werden. Mit Tarnverkehr gibt es einen konstanten Strom identisch aussehenden Verkehrs, unabhängig davon, ob jemand tatsächlich tippt — was es unmöglich macht, echte Nachrichten vom Rauschen zu unterscheiden."),
    section("Was ist Verbindungs-Padding?",
        "Der Server sendet binäre Frames zufälliger Länge (64–512 Bytes zufälliger Daten) an jeden verbundenen Client in zufälligen Intervallen (alle 5–30 Sekunden). Diese Frames sind keine Nachrichten — sie sind reines Rauschen, das der Client stillschweigend ignoriert. In Kombination mit clientseitigem Tarnverkehr stellt das Verbindungs-Padding sicher, dass Netzwerkverkehrsmuster nichts darüber verraten, ob echte Kommunikation stattfindet, wie viele Nachrichten ausgetauscht werden oder wann Teilnehmer aktiv sind."),
    section("Was ist die Paniktaste?",
        "Dreimaliges Antippen der Escape-Taste löscht sofort deine Sitzung. Wenn ausgelöst, sendet nullchat einen Beenden-Befehl an den Server (löscht alle deine Nachrichten), schließt die WebSocket-Verbindung, nullt den Verschlüsselungsschlüssel im Speicher, leert das DOM, löscht sessionStorage und localStorage, leert die Zwischenablage und leitet deinen Browser auf google.com um. Der gesamte Vorgang dauert weniger als eine Sekunde. Wenn der Browser versucht, die Seite aus dem Cache wiederherzustellen (z.B. über die Zurück-Taste), wird die Löschung automatisch erneut ausgelöst. Verwende dies, wenn du sofort alle Beweise des Gesprächs von deinem Bildschirm und Browser löschen musst."),
    section("Was ist der steganographische Modus?",
        "Der steganographische Modus tarnt die nullchat-Oberfläche als Dokumenteneditor. Drücke fünfmal schnell die Shift-Taste, um ihn zu aktivieren. Die gesamte Benutzeroberfläche verwandelt sich — die dunkle Chat-Oberfläche wird durch eine vertraut aussehende Dokumentenbearbeitungsoberfläche mit Symbolleiste und Menüleiste ersetzt. Nachrichten erscheinen als Absätze im Dokumentkörper, und deine Eingabe fügt sich als aktives Tippen ein. Alle Verschlüsselungs-, Lösch-Timer und Sicherheitsfunktionen funktionieren darunter normal weiter.\n\nDies ist nützlich, wenn jemand über deine Schulter schaut oder wenn dein Bildschirm für andere sichtbar ist. Auf den ersten Blick sieht es so aus, als würdest du ein Dokument bearbeiten, nicht ein verschlüsseltes Gespräch führen. Drücke fünfmal Shift erneut, um zur normalen Chat-Ansicht zurückzukehren."),
    section("Löscht nullchat automatisch die Zwischenablage?",
        "Ja. Wenn etwas kopiert wird, während du in einem Chatraum bist, löscht nullchat automatisch deine Zwischenablage nach 15 Sekunden. Die Zwischenablage wird auch gelöscht, wenn du den Tab schließt oder wegnavigierst, und sofort, wenn du die Paniktaste verwendest. Dies verhindert, dass Nachrichteninhalte in deiner Zwischenablage verbleiben, nachdem du das Gespräch verlassen hast."),
    section("Können Sie meine Nachrichten lesen?",
        "Nein. Der Server ist ein einfaches Relay. Er empfängt verschlüsselte Blobs und leitet sie weiter. Der Verschlüsselungsschlüssel wird aus deinem gemeinsamen Geheimnis abgeleitet, das niemals deinen Browser verlässt. Wir haben den Schlüssel nicht. Wir können die Blobs nicht entschlüsseln. Selbst wenn der Server kompromittiert würde, würde der Angreifer nur bedeutungslosen Chiffretext erhalten."),
    section("Können Regierungsbehörden auf meine Nachrichten zugreifen?",
        "Wir können nicht bereitstellen, was wir nicht haben. Es gibt nirgendwo gespeicherte Klartextnachrichten. Es gibt keine Benutzerkonten zum Nachschlagen. Es gibt keine IP-Protokolle zum Übergeben. Die verschlüsselten Blobs werden nach einem festen Zeitplan automatisch gelöscht. Selbst bei einer gültigen gerichtlichen Anordnung wäre das Maximum, was wir liefern könnten, eine Sammlung verschlüsselter Blobs und Raum-Hashes — von denen keiner ohne das gemeinsame Geheimnis nützlich ist, das nur die Teilnehmer kennen."),
    section("Ist nullchat Open Source?",
        "Ja. Der gesamte Code — Client, Server, Verschlüsselung und Infrastrukturkonfiguration — ist öffentlich zur Prüfung verfügbar unter {github_link}. Du kannst überprüfen, ob der auf dem Server laufende Code mit dem Veröffentlichten übereinstimmt, ihn selbst kompilieren oder deine eigene Instanz hosten. Transparenz ist nicht optional für ein Tool, das dich bittet, ihm deine privaten Kommunikationen anzuvertrauen."),
    section("Wer hat nullchat gebaut?",
        "nullchat wurde von Artorias gebaut — einem von Veteranen betriebenen Geheimdiensttechnologie-Unternehmen mit Sitz in New York City. Artorias existiert, um veraltete Systeme abzubauen und die wichtigsten Organisationen und Einzelpersonen mit Werkzeugen auszustatten, die speziell für das Operieren im Verborgenen entwickelt wurden. Im Kern geht es bei Artorias darum, Geheimdienst und Anonymität zu demokratisieren — sicherzustellen, dass die Fähigkeit, sicher zu kommunizieren und ohne Überwachung zu operieren, kein Privileg ist, das wenigen vorbehalten ist. nullchat ist ein Ausdruck dieser Mission: sichere Kommunikation auf das Wesentliche reduziert, ohne Kompromisse bei der kryptographischen Integrität. Erfahre mehr unter {artorias_link}."),
    section("Kann ich nullchat zu meinem Startbildschirm hinzufügen?",
        "Ja. nullchat unterstützt Zum Startbildschirm hinzufügen sowohl auf iOS als auch auf Android. In iOS Safari tippe auf die Teilen-Schaltfläche und wähle \"Zum Home-Bildschirm\". In Android Chrome tippe auf das Menü und wähle \"Zum Startbildschirm hinzufügen\" oder \"App installieren\". Dies erstellt eine eigenständige Verknüpfung, die nullchat ohne Browser-Chrome öffnet — keine Adressleiste, keine Tabs. Es sieht aus und fühlt sich an wie eine native App.\n\nWichtig: nullchat verwendet absichtlich keinen Service Worker und speichert keine Daten offline zwischen. Es gibt keinen Offline-Modus. Die Startbildschirm-Verknüpfung öffnet einfach die Live-Website — nichts wird auf deinem Gerät über die Verknüpfung selbst hinaus gespeichert. Dies ist eine Sicherheitsentscheidung: Das Zwischenspeichern verschlüsselter Chat-Seiten oder Service-Worker-Skripte auf dem Gerät würde forensische Beweise schaffen, dass nullchat verwendet wurde. Die Verknüpfung hinterlässt keine Spur über ihr eigenes Symbol hinaus, das jederzeit gelöscht werden kann."),
]

outpath = "/Users/christian/whisper/lib/i18n/faq.ts"
with open(outpath, 'a') as f:
    write_lang(f, "de", de)

print("German done")
