#!/usr/bin/env python3
"""Append French translations to faq.ts"""

def ts_string(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s

def section(title, body):
    return {"title": title, "body": body}

def write_lang(f, lang, sections):
    f.write(f'  "{lang}": [\n')
    for i, sec in enumerate(sections):
        t = ts_string(sec["title"])
        b = ts_string(sec["body"])
        f.write(f'    {{\n')
        f.write(f'      title: "{t}",\n')
        f.write(f'      body: "{b}",\n')
        f.write(f'    }},\n')
    f.write(f'  ],\n\n')

fr = [
    section("Qu'est-ce que nullchat ?",
        "nullchat est une salle de discussion anonyme, chiffrée de bout en bout, qui ne nécessite aucun compte, aucun e-mail, aucun numéro de téléphone et aucune information personnelle d'aucune sorte. Vous entrez un secret partagé — un mot de passe — et toute autre personne qui entre le même mot de passe arrive dans la même salle. C'est tout."),
    section("Comment rejoindre une salle ?",
        "Vous et la personne avec qui vous souhaitez discuter convenez d'un secret partagé à l'avance — en personne, par téléphone, comme vous voulez. Vous tapez tous les deux ce secret dans nullchat et vous êtes dans la même salle chiffrée. Il n'y a pas de liste de salles, pas de répertoire, aucun moyen de parcourir. Si vous ne connaissez pas le secret, la salle n'existe pas pour vous."),
    section("Comment choisir un secret partagé ?",
        "Votre secret partagé est l'élément le plus important de votre sécurité. C'est à la fois la clé de votre salle et la clé de votre chiffrement — si quelqu'un le devine, il peut tout lire. Traitez-le comme le mot de passe d'un coffre-fort.\n\nChoisissez quelque chose de long, aléatoire et impossible à deviner. Un secret fort comporte au moins 5–6 mots aléatoires ou plus de 20 caractères mixtes. Évitez les noms, les dates, les expressions courantes, les paroles de chansons ou tout ce que quelqu'un pourrait trouver sur vos réseaux sociaux. Ne réutilisez jamais un secret pour différentes conversations ou salles.\n\nPartagez votre secret via un canal sécurisé hors bande — en personne c'est le mieux. Un appel téléphonique est acceptable. Ne l'envoyez jamais par SMS, e-mail, message privé ou toute plateforme qui enregistre les messages. Si vous soupçonnez qu'un secret a été compromis, cessez de l'utiliser immédiatement et convenez d'un nouveau via un canal sécurisé.\n\nL'indicateur de force sur l'écran d'entrée vous donne une idée approximative de la résistance de votre secret aux attaques par force brute, mais aucun indicateur ne remplace le bon jugement. En cas de doute, rendez-le plus long et plus aléatoire."),
    section("Comment fonctionne le chiffrement ?",
        "Lorsque vous entrez votre secret partagé, deux choses se produisent entièrement dans votre navigateur :\n\n1. Le secret est traité par Argon2id — une fonction de dérivation de clé à forte consommation de mémoire — utilisant un sel séparé par domaine pour produire un identifiant de salle. Ce hash est envoyé au serveur pour qu'il sache à quelle salle vous connecter. Le serveur ne voit jamais votre secret réel.\n\n2. Le secret passe par une seconde dérivation Argon2id indépendante (64 Mio de mémoire, 3 itérations) pour produire une clé de chiffrement de 256 bits. Cette clé ne quitte jamais votre navigateur. Argon2id nécessite de grands blocs de RAM par tentative, rendant les attaques par force brute GPU et ASIC contre votre mot de passe des ordres de grandeur plus difficiles que les KDF traditionnels.\n\nChaque message que vous envoyez est chiffré avec NaCl secretbox (XSalsa20-Poly1305) en utilisant cette clé avant de quitter votre appareil. Le serveur reçoit, stocke et relaie uniquement du texte chiffré — des blobs chiffrés qui n'ont aucun sens sans la clé. Nous ne pouvons pas lire vos messages. Personne ne le peut, à moins de connaître le secret partagé."),
    section("Que voit le serveur ?",
        "Le serveur voit :\n• Un hash dérivé d'Argon2id (l'identifiant de salle) — pas votre mot de passe\n• Des blobs de texte chiffré — pas vos messages\n• Le nombre de connexions actives dans une salle\n• Les horodatages de réception des blobs chiffrés\n\nLe serveur ne voit PAS :\n• Votre secret partagé / mot de passe\n• Le contenu de vos messages\n• Votre identité ou nom d'utilisateur (les alias sont chiffrés à l'intérieur des messages)\n• Votre adresse IP (supprimée en périphérie par notre hébergeur)"),
    section("Qu'est-ce que le rembourrage des messages ?",
        "Avant le chiffrement, chaque message est rembourré à un bloc fixe de 8 192 octets en utilisant un préfixe de longueur de 2 octets suivi du contenu du message et de bruit aléatoire. Cela signifie qu'un message court comme « salut » produit exactement la même taille de texte chiffré qu'un message de longueur maximale. Sans rembourrage, un observateur pourrait deviner le contenu du message en se basant sur la longueur du texte chiffré. Le remplissage de bruit aléatoire (pas des zéros) garantit qu'il n'y a aucun motif distinguable dans le texte en clair avant le chiffrement. Le rembourrage élimine entièrement ce canal latéral."),
    section("Qu'est-ce que l'obfuscation des horodatages ?",
        "Les horodatages inclus dans les messages sont arrondis à la minute la plus proche avant le chiffrement. Cela empêche les attaques par corrélation temporelle où un observateur pourrait faire correspondre des modèles de messages entre différents canaux en comparant des horodatages exacts."),
    section("Combien de temps durent les messages ?",
        "Les messages utilisent un système de minuteries à plusieurs niveaux :\n\n• Boîte morte (premier message) : Un message reste chiffré sur le serveur pendant 24 heures maximum, en attendant une réponse. L'expéditeur peut partir et revenir vérifier sans déclencher de compte à rebours. Le simple fait d'entrer dans la salle ne brûle pas le message.\n\n• Les deux utilisateurs présents : Lorsqu'une deuxième personne rejoint la salle, tous les messages non lus commencent immédiatement un compte à rebours de destruction de 5 minutes. Chaque nouveau message envoyé pendant que les deux utilisateurs sont présents s'autodétruit aussi en 5 minutes. Aucune action n'est requise — la présence seule confirme que le message est lu.\n\n• Bouton Reçu : Si vous récupérez un message de boîte morte alors que vous êtes seul dans la salle, vous pouvez appuyer sur le bouton « Reçu » pour confirmer manuellement la réception et démarrer la destruction de 5 minutes. Ce bouton n'apparaît qu'une seule fois — lors de la récupération initiale de la boîte morte — et n'est pas disponible pendant les conversations actives.\n\n• Conversation active : Une fois qu'une salle a vu des réponses, les messages suivants ont une fenêtre de 6 heures si le destinataire n'est pas présent. Si les deux utilisateurs sont connectés, les messages se détruisent en 5 minutes automatiquement.\n\n• Plafond absolu : Tout message non lu est supprimé après l'expiration de son minuteur (24 heures pour les boîtes mortes, 6 heures pour les messages actifs) qu'il ait été confirmé ou non.\n\nIl n'y a pas d'archive, pas de sauvegarde, aucun moyen de récupérer un message supprimé."),
    section("Qu'est-ce que la boîte morte ?",
        "nullchat fonctionne comme une boîte morte numérique. Dans le renseignement traditionnel, une boîte morte est une méthode pour transmettre des informations entre deux personnes sans qu'elles aient besoin de se rencontrer ou d'être au même endroit en même temps. nullchat fonctionne de la même manière.\n\nVous entrez le secret partagé, laissez un message chiffré et vous déconnectez. Le message reste sur le serveur — chiffré et illisible par quiconque, y compris nous — pendant 24 heures maximum. Votre contact entre le même secret quand il est prêt et récupère le message. Lorsque le destinataire rejoint la salle et que les deux utilisateurs sont présents, tous les messages en attente commencent immédiatement un compte à rebours de destruction de 5 minutes — la présence seule est la preuve de réception. Si le destinataire récupère le message alors qu'il est seul, il peut appuyer sur le bouton unique « Reçu » pour confirmer manuellement la réception et démarrer la destruction, ou simplement répondre. Une fois la destruction commencée, le message est définitivement détruit après 5 minutes.\n\nL'expéditeur peut se reconnecter en toute sécurité à tout moment pour vérifier si son message attend toujours — sans déclencher de compte à rebours, tant qu'il est seul dans la salle. Aucune des parties n'a besoin d'être en ligne en même temps. Aucune des parties n'a besoin d'un compte. Aucune des parties n'est identifiable. Le serveur ne sait jamais qui a laissé le message ou qui l'a récupéré — seulement qu'un blob chiffré a été stocké puis récupéré. Après la destruction, il n'y a aucune preuve que l'échange ait eu lieu."),
    section("Combien de temps durent les salles ?",
        "Une salle existe tant qu'elle a des connexions actives ou des messages non expirés. Une fois que la dernière personne se déconnecte et que tous les messages ont expiré ou été détruits, la salle disparaît. Il n'y a pas d'état de salle persistant. Si aucun message n'est jamais envoyé, la salle n'est qu'une connexion en direct — rien n'est stocké, et elle disparaît dès que tout le monde part."),
    section("Qu'est-ce que le bouton Terminer ?",
        "Terminer supprime immédiatement chaque message que vous avez envoyé pendant votre session en cours du serveur pour tous les participants de la salle. Les autres participants verront vos messages disparaître de leur écran en temps réel. Vous êtes ensuite déconnecté de la salle. Utilisez ceci si vous devez partir sans laisser de trace."),
    section("Qu'est-ce que le bouton Quitter ?",
        "Quitter vous déconnecte simplement de la salle. Vos messages restent sur le serveur — les messages non lus continuent d'attendre (jusqu'à 24 heures), et les messages déjà lus continuent leur compte à rebours de destruction de 5 minutes. Si vous rejoignez la salle plus tard, vous obtiendrez un nouvel alias aléatoire — il n'y a aucun moyen de lier vos anciennes et nouvelles identités."),
    section("Que sont les alias aléatoires ?",
        "Lorsque vous entrez dans une salle, un code hexadécimal aléatoire de 8 caractères (comme « a9f2b71c ») vous est attribué comme alias. Cet alias est généré dans votre navigateur, chiffré à l'intérieur de chaque message, et n'est jamais envoyé au serveur en texte clair. Si vous vous déconnectez et vous reconnectez, vous obtenez un nouvel alias. Il n'y a aucun moyen de réserver, choisir ou conserver un alias."),
    section("Y a-t-il une limite de participants ?",
        "Chaque salle supporte jusqu'à 50 connexions simultanées. Si la salle est pleine, vous verrez un message « Salle pleine ». Cette limite existe pour garder les salles intimes et pour prévenir les abus."),
    section("Y a-t-il une limitation de débit ?",
        "Oui. Chaque connexion est limitée à 1 message par seconde. Cela empêche le spam et les abus sans nécessiter de vérification d'identité. Si vous envoyez des messages trop rapidement, vous verrez un bref avis « Ralentissez »."),
    section("Puis-je accéder à nullchat via Tor ?",
        "nullchat est disponible en tant que service caché Tor pour les utilisateurs dans des régions censurées ou toute personne souhaitant une couche supplémentaire d'anonymat. Ouvrez le navigateur Tor et naviguez vers :\n\n{onion_link}\n\nPar défaut, les versions clearnet et Tor se connectent au même backend — les utilisateurs de l'une ou l'autre peuvent communiquer entre eux dans les mêmes salles en utilisant le même secret partagé. Le service .onion passe par le réseau Tor sans Cloudflare, sans CDN et sans infrastructure tierce entre vous et le serveur. Tor achemine votre connexion à travers plusieurs relais chiffrés, de sorte que ni le serveur ni aucun observateur ne peuvent déterminer votre adresse IP réelle ou votre emplacement. Le service .onion utilise du HTTP simple, ce qui est attendu et sûr — Tor lui-même fournit un chiffrement de bout en bout entre votre navigateur et le serveur. Tout le même chiffrement au niveau applicatif (NaCl secretbox, dérivation de clé Argon2id) s'applique par-dessus. Note : Le navigateur Tor doit être réglé sur le niveau de sécurité « Standard » pour que nullchat fonctionne, car l'application nécessite JavaScript."),
    section("Qu'est-ce qu'une salle Tor uniquement ?",
        "En accédant à nullchat via le service caché .onion, vous avez la possibilité d'activer « Salle Tor uniquement » — un interrupteur qui apparaît sur l'écran de saisie du mot de passe. Lorsqu'il est activé, votre salle est placée dans un espace de noms séparé auquel seuls d'autres utilisateurs Tor ayant activé le même interrupteur peuvent accéder. Les utilisateurs du clearnet ne peuvent jamais rejoindre une salle Tor uniquement, même s'ils connaissent le secret partagé.\n\nCela fournit un niveau de sécurité plus élevé que les salles partagées par défaut :\n\n• Les deux parties sont acheminées via le réseau onion multi-sauts de Tor — l'adresse IP réelle ou l'emplacement d'aucune des parties n'est visible par quiconque, y compris le serveur.\n• Aucune recherche DNS, aucun CDN et aucune infrastructure tierce ne touche la connexion à aucun moment.\n• L'analyse de trafic est considérablement plus difficile car les deux côtés bénéficient du rembourrage de relais de Tor combiné au rembourrage de connexion propre à nullchat (trames fictives aléatoires envoyées à des intervalles aléatoires).\n• Il n'y a pas de participant clearnet dont les métadonnées de connexion plus faibles pourraient être corrélées avec la conversation.\n\nVous n'êtes aussi anonyme que le maillon le plus faible de la conversation. Dans une salle par défaut, la connexion d'un participant clearnet touche des résolveurs DNS, une infrastructure CDN et un routage Internet standard — tout cela peut être observé ou faire l'objet d'une injonction pour obtenir des métadonnées sur qui s'est connecté, quand et d'où. L'interrupteur Tor uniquement élimine entièrement ce risque en garantissant que chaque participant a le même niveau d'anonymat au niveau du réseau.\n\nLes deux parties doivent convenir d'activer l'interrupteur — cela fonctionne de la même manière que convenir du secret partagé. L'en-tête du chat affiche « TOR UNIQUEMENT » en vert lorsqu'il est actif, ou « CLEARNET » en rouge pour les salles standard, pour que vous sachiez toujours dans quel mode vous êtes."),
    section("Qu'est-ce que le délai d'inactivité ?",
        "Si vous êtes inactif pendant 15 minutes — sans taper, sans toucher, sans faire défiler — nullchat vous déconnectera automatiquement et vous ramènera à l'écran de saisie du mot de passe. Un avertissement apparaît à 13 minutes vous donnant la possibilité de rester. Cela protège votre session si vous vous éloignez de votre appareil, empêchant les messages de se détruire pendant que personne ne les lit activement, et garantissant que le chat n'est pas laissé visible sur un écran sans surveillance."),
    section("Qu'en est-il des adresses IP ?",
        "Sur le clearnet (nullchat.org), l'application est hébergée sur le réseau de périphérie de Cloudflare. Votre adresse IP est gérée au niveau de l'infrastructure et n'est jamais lue, enregistrée ou stockée par le code de l'application. Le code du serveur n'accède pas aux en-têtes IP. Nous n'avons aucun mécanisme pour vous identifier par adresse réseau.\n\nSur le service caché Tor (.onion), votre adresse IP n'est jamais visible par le serveur — le routage onion de Tor garantit un anonymat complet au niveau du réseau. Le serveur ne voit que des connexions provenant du réseau Tor, sans aucun moyen de les retracer jusqu'à vous."),
    section("Y a-t-il des cookies ou des traceurs ?",
        "Non. nullchat ne définit aucun cookie, n'utilise aucune analytique, ne charge aucun script tiers, n'intègre aucun pixel de suivi et ne fait aucune requête externe. Les en-têtes de Politique de Sécurité de Contenu appliquent cela au niveau du navigateur. Vous pouvez le vérifier dans les outils de développement de votre navigateur."),
    section("Pourquoi ne puis-je pas envoyer de liens, d'images ou de fichiers ?",
        "Par conception. nullchat est uniquement textuel — aucun lien, image, pièce jointe ou média d'aucune sorte ne peut être envoyé ou affiché. C'est une décision de sécurité délibérée, pas une limitation. Les liens cliquables et les médias intégrés sont la principale surface d'attaque pour les exploits zero-day utilisés par les logiciels espions commerciaux comme Pegasus, Predator et des outils de surveillance similaires. Un seul lien ou fichier malveillant peut compromettre silencieusement un appareil entier. En réduisant le chat au texte brut uniquement, nullchat élimine entièrement ce vecteur d'attaque. Il n'y a rien à cliquer, rien à télécharger et rien à afficher — ce qui signifie rien à exploiter."),
    section("Puis-je copier ou capturer des messages ?",
        "nullchat décourage activement la capture du contenu des messages. La sélection de texte et la copie sont désactivées dans la zone de chat, les menus contextuels du clic droit sont bloqués, et les raccourcis clavier courants de capture d'écran sont interceptés. L'API de Capture d'Écran du navigateur est également bloquée via les en-têtes Permissions-Policy, empêchant les outils d'enregistrement d'écran basés sur le web de capturer la page.\n\nCe sont des protections basées sur la friction, pas des garanties absolues. Un utilisateur déterminé peut toujours photographier son écran avec un autre appareil ou utiliser des outils au niveau du système d'exploitation qui contournent les restrictions du navigateur. L'objectif est de rendre la capture occasionnelle difficile et de renforcer l'attente que les conversations dans nullchat ne sont pas destinées à être sauvegardées."),
    section("Qu'est-ce que le trafic leurre ?",
        "nullchat envoie automatiquement des messages factices chiffrés à des intervalles aléatoires (toutes les 10–60 secondes) pendant que vous êtes connecté à une salle. Ces messages leurres sont indiscernables des vrais messages — ils ont la même taille (grâce au rembourrage fixe), sont chiffrés avec la même clé et relayés par le même chemin serveur. Le client du destinataire les rejette silencieusement après déchiffrement.\n\nLe trafic leurre déjoue l'analyse de trafic. Sans lui, un observateur surveillant le trafic réseau pourrait déterminer quand une communication réelle a lieu en se basant sur le moment où les blobs chiffrés sont envoyés. Avec les leurres, il y a un flux constant de trafic d'apparence identique, que quelqu'un soit en train de taper ou non — rendant impossible la distinction entre vrais messages et bruit."),
    section("Qu'est-ce que le rembourrage de connexion ?",
        "Le serveur envoie des trames binaires de longueur aléatoire (64–512 octets de données aléatoires) à chaque client connecté à des intervalles aléatoires (toutes les 5–30 secondes). Ces trames ne sont pas des messages — c'est du bruit pur que le client ignore silencieusement. Combiné au trafic leurre côté client, le rembourrage de connexion garantit que les modèles de trafic réseau ne révèlent rien sur la présence d'une communication réelle, le nombre de messages échangés ou le moment où les participants sont actifs."),
    section("Qu'est-ce que la touche panique ?",
        "Appuyer trois fois sur la touche Échap efface instantanément votre session. Lorsqu'elle est déclenchée, nullchat envoie une commande de terminaison au serveur (supprimant tous vos messages), ferme la connexion WebSocket, met à zéro la clé de chiffrement en mémoire, vide le DOM, efface sessionStorage et localStorage, vide le presse-papiers et redirige votre navigateur vers google.com. L'ensemble du processus prend moins d'une seconde. Si le navigateur tente de restaurer la page depuis le cache (par exemple, via le bouton retour), l'effacement est automatiquement redéclenché. Utilisez ceci si vous devez effacer immédiatement toute preuve de la conversation de votre écran et de votre navigateur."),
    section("Qu'est-ce que le mode stéganographique ?",
        "Le mode stéganographique déguise l'interface de nullchat en éditeur de documents. Appuyez cinq fois rapidement sur Shift pour l'activer. Toute l'interface se transforme — l'interface sombre du chat est remplacée par une interface d'édition de documents d'apparence familière avec barre d'outils et barre de menus. Les messages apparaissent comme des paragraphes dans le corps du document, et votre saisie se fond comme de la frappe active. Tout le chiffrement, les minuteries de destruction et les fonctions de sécurité continuent de fonctionner normalement en dessous.\n\nC'est utile si quelqu'un regarde par-dessus votre épaule ou si votre écran est visible par d'autres. Au premier coup d'œil, on dirait que vous éditez un document, pas que vous avez une conversation chiffrée. Appuyez cinq fois sur Shift à nouveau pour revenir à la vue de chat normale."),
    section("nullchat efface-t-il automatiquement le presse-papiers ?",
        "Oui. Si quoi que ce soit est copié pendant que vous êtes dans une salle de chat, nullchat efface automatiquement votre presse-papiers après 15 secondes. Le presse-papiers est également effacé lorsque vous fermez l'onglet ou naviguez ailleurs, et immédiatement si vous utilisez la touche panique. Cela empêche le contenu des messages de rester dans votre presse-papiers après que vous ayez quitté la conversation."),
    section("Pouvez-vous lire mes messages ?",
        "Non. Le serveur est un simple relais. Il reçoit des blobs chiffrés et les transmet. La clé de chiffrement est dérivée de votre secret partagé, qui ne quitte jamais votre navigateur. Nous n'avons pas la clé. Nous ne pouvons pas déchiffrer les blobs. Même si le serveur était compromis, l'attaquant n'obtiendrait que du texte chiffré sans signification."),
    section("Les agences gouvernementales peuvent-elles accéder à mes messages ?",
        "Nous ne pouvons pas fournir ce que nous n'avons pas. Il n'y a aucun message en texte clair stocké nulle part. Il n'y a aucun compte utilisateur à consulter. Il n'y a aucun journal IP à remettre. Les blobs chiffrés s'auto-suppriment selon un calendrier fixe. Même sous une ordonnance judiciaire valide, le maximum que nous pourrions produire est une collection de blobs chiffrés et de hashes de salle — aucun desquels n'est utile sans le secret partagé que seuls les participants connaissent."),
    section("nullchat est-il open source ?",
        "Oui. L'intégralité du code — client, serveur, chiffrement et configuration d'infrastructure — est publiquement disponible pour audit sur {github_link}. Vous pouvez vérifier que le code exécuté sur le serveur correspond à ce qui est publié, le compiler vous-même ou héberger votre propre instance. La transparence n'est pas optionnelle pour un outil qui vous demande de lui faire confiance avec vos communications privées."),
    section("Qui a construit nullchat ?",
        "nullchat est construit par Artorias — une entreprise de technologie du renseignement dirigée par des vétérans, basée à New York. Artorias existe pour démanteler les systèmes obsolètes et armer les organisations et individus les plus importants avec des outils conçus spécifiquement pour opérer dans l'ombre. En son cœur, Artorias vise à démocratiser le renseignement et l'anonymat — en s'assurant que la capacité de communiquer en toute sécurité et d'opérer sans surveillance n'est pas un privilège réservé à quelques-uns. nullchat est une expression de cette mission : une communication sécurisée réduite à son essence, sans compromis sur l'intégrité cryptographique. En savoir plus sur {artorias_link}."),
    section("Puis-je ajouter nullchat à mon écran d'accueil ?",
        "Oui. nullchat supporte l'ajout à l'écran d'accueil sur iOS et Android. Sur iOS Safari, appuyez sur le bouton de partage et sélectionnez « Ajouter à l'écran d'accueil ». Sur Android Chrome, appuyez sur le menu et sélectionnez « Ajouter à l'écran d'accueil » ou « Installer l'appli ». Cela crée un raccourci autonome qui ouvre nullchat sans le chrome du navigateur — pas de barre d'adresse, pas d'onglets. L'apparence et le fonctionnement sont ceux d'une application native.\n\nImportant : nullchat n'utilise délibérément pas de service worker et ne met aucune donnée en cache hors ligne. Il n'y a pas de mode hors ligne. Le raccourci de l'écran d'accueil ouvre simplement le site en direct — rien n'est stocké sur votre appareil au-delà du raccourci lui-même. C'est une décision de sécurité : mettre en cache des pages de chat chiffrées ou des scripts de service worker sur l'appareil créerait des preuves forensiques que nullchat a été utilisé. Le raccourci ne laisse aucune trace au-delà de sa propre icône, qui peut être supprimée à tout moment."),
]

outpath = "/Users/christian/whisper/lib/i18n/faq.ts"
with open(outpath, 'a') as f:
    write_lang(f, "fr", fr)

print("French done")
